// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://spvlugytjckpjwlkasah.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNwdmx1Z3l0amNrcGp3bGthc2FoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc0NzQwOTIsImV4cCI6MjA1MzA1MDA5Mn0.4u7m_w-EOS7tGSbuX1U5dkxjJFrNnXSP_mdVtbMHQNk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);